# Analisis Data Deforestasi Pulau Sumatra Indonesia

## Tujuan
Buktikan bahwa angka deforestasi pulau sumatra lebih dari angka deforestasi seluruh daerah indonesia lainnya (Indonesia minus sumatra) selama tahun 2013-2020.

### Hipotesis
* Jumlah deforestasi per tahun seluruh provinsi di sumatra > Jumlah deforestasi per tahun seluruh provinsi selain sumatra

### Tahapan
1. Pra-pemrosesan Data
2. Analisis Data Exploratif (EDA)
3. Analisis Data Statistik (Hyphothesis Testing)

## 1. Pra-pemrosesan Data

In [1]:
# Import Library
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats as st
import warnings
warnings.filterwarnings('ignore')

### 1.1. Memuat Data

In [2]:
data = pd.read_excel('Indo_60_1641792743_fix.xls', sheet_name='B Indonesia')
data

,provinsi,kh_1314,apl_1314,deforestasi_1314,kh_1415,apl_1415,deforestasi_1415,kh_1516,apl_1516,deforestasi_1516,...,deforestasi_1617,kh_1718,apl_1718,deforestasi_1718,kh_1819,apl_1819,deforestasi_1819,kh_1920,apl_1920,deforestasi_1920
0,Aceh,3363.9,4284.2,7648.1,-72.1,3303.5,3231.5,12523,10548.6,23071.6,...,15515.7,3216.4,4285.8,7502.2,6737.5,4870.5,11608,1195.3,722.6,1917.9
1,Sumatera Utara,4675.2,1465.3,6140.5,15450.3,5215.4,20665.7,7907.3,1807,9714.3,...,22549.6,4255.7,3063.4,7319.1,9583.9,2818.5,12402.4,470.4,763.2,1233.6
2,Sumatera Barat,3330.3,1725.7,5056,8813.9,1685.1,10498.9,8199.1,-381.4,7817.8,...,8680,3824.1,1689.9,5514,7626,1698.9,9324.8,700.2,74.4,774.6
3,Riau,180786.5,21152.9,201939.4,124314.6,11216.1,135530.7,18365.4,5825.4,24190.9,...,6981.6,23672.3,20042.5,43714.8,136998.3,5012.9,142011.1,5672.6,893.6,6566.2
4,Jambi,-12809.6,2868.1,-9941.5,15422.4,1470.7,16893.1,24263,558.4,24821.4,...,32871.3,5994.4,3241.2,9235.6,26109.6,1272.3,27382,4035.0,451.9,4486.9
5,Sumatera Selatan,2853.5,673.7,3527.2,271032.8,19744.2,290777,3089.3,1204.8,4294.2,...,22286.6,3619.4,121.6,3741,57857.6,2797.5,60655.1,-2353.6,41.6,-2312.0
6,Bengkulu,12106.8,-37.4,12069.4,2139.6,1993.5,4133.1,1493.5,305.2,1798.8,...,5091.5,7064,642.4,7706.4,1959.4,201.2,2160.6,3022.5,337.3,3359.8
7,Lampung,197.8,-33.9,163.9,12909.9,3790.3,16700.2,1384.1,-170.5,1213.6,...,4420.3,1104.7,253.8,1358.5,182.3,443.2,625.4,384.1,79.2,463.3
8,Kepulauan Bangka Belitung,1209.7,489.7,1699.4,13594.7,5697.7,19292.3,344.8,1347.5,1692.3,...,3181.7,3559.1,186.7,3745.8,1574.3,580.2,2154.4,89.3,29.1,118.4
9,Kepulauan Riau,4.3,0.4,4.6,1191.5,130.4,1322,2651.4,-1953.7,697.7,...,5662.8,503.9,-646.4,-142.5,356.7,205.3,562,980.3,334.1,1314.4
10,DKI Jakarta,-,-,-,-,-,-,-,-,-,...,-0.8,-,-,-,-,-,-,0.0,0.0,0.0
11,Jawa Barat,-10979.5,-3901,-14880.5,1750.5,4309.5,6060,-,-,-,...,-188,2598.9,3789.6,6388.5,3782.4,1194.9,4977.4,0.0,0.0,0.0
12,Jawa Tengah,-79.2,-15.1,-94.3,1589.5,3641.9,5231.4,-,-,-,...,-,2004.7,1110.8,3115.6,1859.6,44.5,1904,0.0,0.0,0.0
13,DI Yogyakarta,0.9,31.9,32.8,51.8,-,51.8,-,-,-,...,-270.2,2.4,587.4,589.8,141.4,185,326.4,0.0,0.0,0.0
14,Jawa Timur,5452.2,2044.9,7497.1,3621,4128.1,7749.2,-,-,-,...,-,3298.6,5511.7,8810.3,5066.4,738.3,5804.7,0.0,0.0,0.0
15,Banten,-237.3,-28.7,-266.1,1282.2,529.2,1811.5,-,-,-,...,-5262.1,-523.6,240.6,-283.1,67.3,16.1,83.4,0.0,34.3,34.3
16,Bali,110,20.2,130.2,77.5,0,77.5,4096,3359.5,7455.5,...,234.2,99.5,177.4,276.9,89.3,1.7,91,43.8,1.2,45.0
17,Nusa Tenggara Barat,-,-,-,8896.4,186.8,9083.2,12561.9,9800.5,22362.4,...,-14802.7,7065.6,3170.7,10236.4,12382.4,3589.4,15971.9,10571.9,2436.0,13007.9
18,Nusa Tenggara Timur,138.9,-30,108.8,2962.7,10969.3,13932,-,-,-,...,-,6037.1,11652.9,17689.9,1279.2,2233.6,3512.8,2579.3,5710.2,8289.5
19,Kalimantan Barat,7872.8,22046.8,29919.6,5754,34723.2,40477.2,60146.3,64809.7,124956,...,19296.9,13157.7,29133.7,42291.4,15109.1,8985.9,24095,6546.6,9787.9,16334.5
20,Kalimantan Tengah,48370.7,10464.9,58835.6,163240,23402,186642,88816.2,9313,98129.2,...,116782.8,20234.7,7005.6,27240.3,17974.3,8265.8,26240.2,3206.4,3705.9,6912.3
21,Kalimantan Selatan,5191.9,1746.6,6938.5,34631.5,12072.3,46703.8,26180.6,6944.6,33125.1,...,-681.8,5396,8972.6,14368.6,6309.9,1789.4,8099.3,5247.8,2299.4,7547.2
22,Kalimantan Timur dan Kalimantan Utara,16610.8,21728.7,38339.4,36403.9,64526.9,100930.8,57104.9,51577,108682,...,94981.8,26808,38386.2,65194.2,43031.6,26552.9,69584.6,2792.7,7867.8,10660.5
23,Sulawesi Utara,2249.8,1528.3,3778.1,795.1,512.5,1307.5,1838.6,514,2352.6,...,605.3,3135,767.6,3902.6,213,47.8,260.8,231.8,167.6,399.4
24,Sulawesi Tengah,1880.1,2833.9,4714,10546.3,10829.9,21376.3,16045.5,10043.2,26088.6,...,44523.9,11522.7,10424.6,21947.3,2292.4,1499.4,3791.8,5270.8,4232.3,9503.1
25,Sulawesi Selatan,2461.6,892.3,3354,8765.8,1580.8,10346.6,24738.8,5198.5,29937.2,...,9274.1,2528.3,1070,3598.2,1387.7,628,2015.7,386.5,532.6,919.1
26,Sulawesi Tenggara,1485,883.3,2368.3,5475.4,1641.2,7116.7,12399,2966.1,15365.2,...,14956.3,20382.1,10451.8,30834,4544.1,2013.1,6557.2,2794.5,389.9,3184.4
27,Gorontalo,2228,358,2586.1,13146.6,1704.8,14851.4,2074.8,167.7,2242.5,...,-24.6,-837,497.4,-339.6,261.3,116.8,378.1,737.1,330.8,1067.9
28,Sulawesi Barat,428.5,500.6,929,1772,565.5,2337.5,7289.5,2235.2,9524.7,...,1413,566.4,361.4,927.8,-229.2,0.4,-228.8,204.7,11.0,215.7
29,Maluku,589.5,322.7,912.2,2870.2,2063.2,4933.5,6803.9,96.5,6900.5,...,1410.5,2967.5,749.4,3716.9,1214.7,57.2,1271.8,8534.0,733.4,9267.4
30,Maluku Utara,168.4,1400.7,1569.1,10321.6,1629.9,11951.5,22730.5,3061.7,25792.2,...,22033.2,8903,2917.2,11820.2,1780.7,546.2,2326.8,1506.8,103.0,1609.8
31,Papua Barat,1400.1,448.8,1848.9,2696,9611.7,12307.7,6101.6,4119.5,10221.1,...,31228.7,-1683.9,314.4,-1369.5,1855.3,3440.8,5296.1,413.5,1494.9,1908.4
32,Papua,11472.4,8970.6,20443.1,34159.7,33698.2,67857.9,2117.2,4612.4,6729.6,...,17259.1,32846.1,45941.3,78787.4,6468.1,4744.1,11212.2,1731.4,4898.9,6630.3
33,INDONESIA,292533.9,104837.9,397370.9,815607.5,276574,1092181.5,431266.3,197910.6,629176.9,...,480010.8,223323.9,216115.2,439439.1,375866.7,86591.8,462458.5,66995.7,48464.1,115459.8

### 1.2. Mengeksplorasi Data Awal

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   provinsi          34 non-null     object
 1   kh_1314           34 non-null     object
 2   apl_1314          34 non-null     object
 3   deforestasi_1314  34 non-null     object
 4   kh_1415           34 non-null     object
 5   apl_1415          34 non-null     object
 6   deforestasi_1415  34 non-null     object
 7   kh_1516           34 non-null     object
 8   apl_1516          34 non-null     object
 9   deforestasi_1516  34 non-null     object
 10  kh_1617           34 non-null     object
 11  apl_1617          34 non-null     object
 12  deforestasi_1617  34 non-null     object
 13  kh_1718           34 non-null     object
 14  apl_1718          34 non-null     object
 15  deforestasi_1718  34 non-null     object
 16  kh_1819           34 non-null     object
 17  apl_1819          34 non-null     object
 18  deforestasi_1819  34 non-null     object
 19  kh_1920           34 non-null     float64
 20  apl_1920          34 non-null     float64
 21  deforestasi_1920  34 non-null     float64
dtypes: float64(3), object(19)
memory usage: 6.0+ KB

**Deskripsi data**: 


- `provinsi` — nama provinsi di Indonesia
- `kh_1314` — kawasan hutan tahun 2013-2014
- `apl_1314` — Areal Penggunaan Lain / Bukan Kawasan Hutan 2013-2014
- `deforestasi_1314` — Total Deforestasi 2013-2014
- `kh_1415` — kawasan hutan tahun 2014-2015
- `apl_1415` — Areal Penggunaan Lain / Bukan Kawasan Hutan 2014-2015
- `deforestasi_1415` — Total Deforestasi 2014-2015
- `kh_1516` — kawasan hutan tahun 2015-2016
- `apl_1516` — Areal Penggunaan Lain / Bukan Kawasan Hutan 2015-2016
- `deforestasi_1516` — Total Deforestasi 2015-2016
- `kh_1617` — kawasan hutan tahun 2016-2017
- `apl_1617` — Areal Penggunaan Lain / Bukan Kawasan Hutan 2016-2017
- `deforestasi_1617` — Total Deforestasi 2016-2017
- `kh_1718` — kawasan hutan tahun 2017-2018
- `apl_1718` — Areal Penggunaan Lain / Bukan Kawasan Hutan 2017-2018
- `deforestasi_1718` — Total Deforestasi 2017-2018
- `kh_1819` — kawasan hutan tahun 2018-2019
- `apl_1819` — Areal Penggunaan Lain / Bukan Kawasan Hutan 2018-2019
- `deforestasi_1819` — Total Deforestasi 2018-2019
- `kh_1920` — kawasan hutan tahun 2019-2020
- `apl_1920` — Areal Penggunaan Lain / Bukan Kawasan Hutan 2019-2020
- `deforestasi_1920` — Total Deforestasi 2019-2020

**Kesimpulan sementara:**

* Data berupa object, harusnya dalam float. Hal ini diakibatkan terdapat data (-)

In [4]:
# Replcae (-) with 0
data = data.replace('-', 0)

In [5]:
# Convert all float except the first columns
def convert_to_float(df, except_col):
    float_cols = [col for col in df.columns if col != except_col]

    # Convert all columns in float_cols to float
    df[float_cols] = df[float_cols].astype(float)
    
    return df

In [6]:
data = convert_to_float(data, 'provinsi')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   provinsi          34 non-null     object
 1   kh_1314           34 non-null     float64
 2   apl_1314          34 non-null     float64
 3   deforestasi_1314  34 non-null     float64
 4   kh_1415           34 non-null     float64
 5   apl_1415          34 non-null     float64
 6   deforestasi_1415  34 non-null     float64
 7   kh_1516           34 non-null     float64
 8   apl_1516          34 non-null     float64
 9   deforestasi_1516  34 non-null     float64
 10  kh_1617           34 non-null     float64
 11  apl_1617          34 non-null     float64
 12  deforestasi_1617  34 non-null     float64
 13  kh_1718           34 non-null     float64
 14  apl_1718          34 non-null     float64
 15  deforestasi_1718  34 non-null     float64
 16  kh_1819           34 non-null     float64
 17  apl_1819          34 non-null     float64
 18  deforestasi_1819  34 non-null     float64
 19  kh_1920           34 non-null     float64
 20  apl_1920          34 non-null     float64
 21  deforestasi_1920  34 non-null     float64
dtypes: float64(21), object(1)
memory usage: 6.0+ KB

In [8]:
# Check statistical data
data.describe()

,kh_1314,apl_1314,deforestasi_1314,kh_1415,apl_1415,deforestasi_1415,kh_1516,apl_1516,deforestasi_1516,kh_1617,...,deforestasi_1617,kh_1718,apl_1718,deforestasi_1718,kh_1819,apl_1819,deforestasi_1819,kh_1920,apl_1920,deforestasi_1920
count,34.000000,34.000000,34.000000,34.000000,34.000000,3.400000e+01,34.000000,34.000000,34.000000,34.000000,...,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
mean,17207.879412,6166.911765,23374.758824,47976.905882,16269.052941,6.424597e+04,25368.602941,11641.794118,37010.408824,17481.370588,...,28235.926471,13136.697059,12712.658824,25849.355882,22109.802941,5093.635294,27203.432353,3940.923529,2850.829412,6791.752941
std,58144.945266,18556.230151,75302.626538,146450.573955,47894.051449,1.916403e+05,74398.261660,35679.151092,109085.989675,52566.481337,...,84059.145750,38097.362435,37593.781952,75472.700559,67503.976902,15180.046703,81727.066273,11478.979284,8412.340034,19703.945237
min,-12809.600000,-3901.000000,-14880.500000,-72.100000,0.000000,0.000000e+00,0.000000,-1953.700000,0.000000,-8915.400000,...,-14802.700000,-1683.900000,-646.400000,-1369.500000,-229.200000,0.000000,-228.800000,-2353.600000,0.000000,-2312.000000
25%,117.225000,5.350000,114.150000,1755.875000,1498.225000,4.333200e+03,1411.450000,0.000000,1333.275000,0.000000,...,0.000000,1329.700000,395.400000,1797.775000,571.200000,189.050000,787.000000,118.150000,36.125000,142.725000
50%,1682.550000,778.500000,2477.200000,7259.900000,3472.700000,1.122520e+04,6452.750000,1577.250000,7636.650000,3081.600000,...,5377.150000,3589.250000,2303.550000,6853.800000,2125.900000,1233.600000,4384.600000,858.700000,363.600000,1462.100000
75%,5062.725000,2636.650000,7357.450000,14965.475000,10934.450000,2.119865e+04,17785.425000,5668.675000,24663.775000,15085.100000,...,21349.125000,8443.650000,8480.850000,16859.575000,9094.425000,3285.225000,12203.800000,3160.425000,2098.275000,6841.800000
max,292533.900000,104837.900000,397370.900000,815607.500000,276574.000000,1.092182e+06,431266.300000,197910.600000,629176.900000,297183.200000,...,480010.800000,223323.900000,216115.200000,439439.100000,375866.700000,86591.800000,462458.500000,66995.700000,48464.100000,115459.800000

**Kesimpulan:**

* Data telah diubah menjadi float.
* Tidak ada data yang hilang.
* Tidak ada data yang duplikat.

## 2. Analisis Data Exploratif (EDA)

In [9]:
data['provinsi'].unique()

array(['Aceh', 'Sumatera Utara', 'Sumatera Barat', 'Riau', 'Jambi',
       'Sumatera Selatan', 'Bengkulu', 'Lampung',
       'Kepulauan Bangka Belitung', 'Kepulauan Riau', 'DKI Jakarta',
       'Jawa Barat', 'Jawa Tengah', 'DI Yogyakarta', 'Jawa Timur',
       'Banten', 'Bali', 'Nusa Tenggara Barat', 'Nusa Tenggara Timur',
       'Kalimantan Barat', 'Kalimantan Tengah', 'Kalimantan Selatan',
       'Kalimantan Timur dan Kalimantan Utara ', 'Sulawesi Utara',
       'Sulawesi Tengah', 'Sulawesi Selatan', 'Sulawesi Tenggara',
       'Gorontalo', 'Sulawesi Barat', 'Maluku', 'Maluku Utara',
       'Papua Barat', 'Papua', 'INDONESIA'], dtype=object)

Provinsi yang ada di Sumatera adalah : Aceh, Sumatera Utara, Sumatera Barat, Riau, Jambi, Sumatera Selatan, Bengkulu, Lampung, Kepulauan Bangka Belitung, dan Kepulauan Riau.

In [10]:
# Take sumatera province only
sumatera_data = data.iloc[0:10]

In [11]:
# Take only total deforestasi data and add new sum column
sumatera_data_deforestasi = sumatera_data.filter(like='deforestasi')
sumatera_data_deforestasi.insert(0, 'provinsi', data['provinsi'])
sumatera_data_deforestasi['sum'] = sumatera_data_deforestasi.iloc[:, 1:].sum(axis=1)

In [12]:
sumatera_data_deforestasi

,provinsi,deforestasi_1314,deforestasi_1415,deforestasi_1516,deforestasi_1617,deforestasi_1718,deforestasi_1819,deforestasi_1920,sum
0,Aceh,7648.1,3231.5,23071.6,15515.7,7502.2,11608.0,1917.9,70495.0
1,Sumatera Utara,6140.5,20665.7,9714.3,22549.6,7319.1,12402.4,1233.6,80025.2
2,Sumatera Barat,5056.0,10498.9,7817.8,8680.0,5514.0,9324.8,774.6,47666.1
3,Riau,201939.4,135530.7,24190.9,6981.6,43714.8,142011.1,6566.2,560934.7
4,Jambi,-9941.5,16893.1,24821.4,32871.3,9235.6,27382.0,4486.9,105748.8
5,Sumatera Selatan,3527.2,290777.0,4294.2,22286.6,3741.0,60655.1,-2312.0,382969.1
6,Bengkulu,12069.4,4133.1,1798.8,5091.5,7706.4,2160.6,3359.8,36319.6
7,Lampung,163.9,16700.2,1213.6,4420.3,1358.5,625.4,463.3,24945.2
8,Kepulauan Bangka Belitung,1699.4,19292.3,1692.3,3181.7,3745.8,2154.4,118.4,31884.3
9,Kepulauan Riau,4.6,1322.0,697.7,5662.8,-142.5,562.0,1314.4,9421.0

In [13]:
# Take all province except sumatera province
outside_sumatera_data = data.iloc[10:33]

In [14]:
outside_sumatera_data

,provinsi,kh_1314,apl_1314,deforestasi_1314,kh_1415,apl_1415,deforestasi_1415,kh_1516,apl_1516,deforestasi_1516,...,deforestasi_1617,kh_1718,apl_1718,deforestasi_1718,kh_1819,apl_1819,deforestasi_1819,kh_1920,apl_1920,deforestasi_1920
10,DKI Jakarta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Jawa Barat,-10979.5,-3901.0,-14880.5,1750.5,4309.5,6060.0,0.0,0.0,0.0,...,-188.0,2598.9,3789.6,6388.5,3782.4,1194.9,4977.4,0.0,0.0,0.0
12,Jawa Tengah,-79.2,-15.1,-94.3,1589.5,3641.9,5231.4,0.0,0.0,0.0,...,0.0,2004.7,1110.8,3115.6,1859.6,44.5,1904.0,0.0,0.0,0.0
13,DI Yogyakarta,0.9,31.9,32.8,51.8,0.0,51.8,0.0,0.0,0.0,...,-270.2,2.4,587.4,589.8,141.4,185.0,326.4,0.0,0.0,0.0
14,Jawa Timur,5452.2,2044.9,7497.1,3621.0,4128.1,7749.2,0.0,0.0,0.0,...,0.0,3298.6,5511.7,8810.3,5066.4,738.3,5804.7,0.0,0.0,0.0
15,Banten,-237.3,-28.7,-266.1,1282.2,529.2,1811.5,0.0,0.0,0.0,...,-5262.1,-523.6,240.6,-283.1,67.3,16.1,83.4,0.0,34.3,34.3
16,Bali,110.0,20.2,130.2,77.5,0.0,77.5,4096.0,3359.5,7455.5,...,234.2,99.5,177.4,276.9,89.3,1.7,91.0,43.8,1.2,45.0
17,Nusa Tenggara Barat,0.0,0.0,0.0,8896.4,186.8,9083.2,12561.9,9800.5,22362.4,...,-14802.7,7065.6,3170.7,10236.4,12382.4,3589.4,15971.9,10571.9,2436.0,13007.9
18,Nusa Tenggara Timur,138.9,-30.0,108.8,2962.7,10969.3,13932.0,0.0,0.0,0.0,...,0.0,6037.1,11652.9,17689.9,1279.2,2233.6,3512.8,2579.3,5710.2,8289.5
19,Kalimantan Barat,7872.8,22046.8,29919.6,5754.0,34723.2,40477.2,60146.3,64809.7,124956.0,...,19296.9,13157.7,29133.7,42291.4,15109.1,8985.9,24095.0,6546.6,9787.9,16334.5
20,Kalimantan Tengah,48370.7,10464.9,58835.6,163240.0,23402.0,186642.0,88816.2,9313.0,98129.2,...,116782.8,20234.7,7005.6,27240.3,17974.3,8265.8,26240.2,3206.4,3705.9,6912.3
21,Kalimantan Selatan,5191.9,1746.6,6938.5,34631.5,12072.3,46703.8,26180.6,6944.6,33125.1,...,-681.8,5396.0,8972.6,14368.6,6309.9,1789.4,8099.3,5247.8,2299.4,7547.2
22,Kalimantan Timur dan Kalimantan Utara,16610.8,21728.7,38339.4,36403.9,64526.9,100930.8,57104.9,51577.0,108682.0,...,94981.8,26808.0,38386.2,65194.2,43031.6,26552.9,69584.6,2792.7,7867.8,10660.5
23,Sulawesi Utara,2249.8,1528.3,3778.1,795.1,512.5,1307.5,1838.6,514.0,2352.6,...,605.3,3135.0,767.6,3902.6,213.0,47.8,260.8,231.8,167.6,399.4
24,Sulawesi Tengah,1880.1,2833.9,4714.0,10546.3,10829.9,21376.3,16045.5,10043.2,26088.6,...,44523.9,11522.7,10424.6,21947.3,2292.4,1499.4,3791.8,5270.8,4232.3,9503.1
25,Sulawesi Selatan,2461.6,892.3,3354.0,8765.8,1580.8,10346.6,24738.8,5198.5,29937.2,...,9274.1,2528.3,1070.0,3598.2,1387.7,628.0,2015.7,386.5,532.6,919.1
26,Sulawesi Tenggara,1485.0,883.3,2368.3,5475.4,1641.2,7116.7,12399.0,2966.1,15365.2,...,14956.3,20382.1,10451.8,30834.0,4544.1,2013.1,6557.2,2794.5,389.9,3184.4
27,Gorontalo,2228.0,358.0,2586.1,13146.6,1704.8,14851.4,2074.8,167.7,2242.5,...,-24.6,-837.0,497.4,-339.6,261.3,116.8,378.1,737.1,330.8,1067.9
28,Sulawesi Barat,428.5,500.6,929.0,1772.0,565.5,2337.5,7289.5,2235.2,9524.7,...,1413.0,566.4,361.4,927.8,-229.2,0.4,-228.8,204.7,11.0,215.7
29,Maluku,589.5,322.7,912.2,2870.2,2063.2,4933.5,6803.9,96.5,6900.5,...,1410.5,2967.5,749.4,3716.9,1214.7,57.2,1271.8,8534.0,733.4,9267.4
30,Maluku Utara,168.4,1400.7,1569.1,10321.6,1629.9,11951.5,22730.5,3061.7,25792.2,...,22033.2,8903.0,2917.2,11820.2,1780.7,546.2,2326.8,1506.8,103.0,1609.8
31,Papua Barat,1400.1,448.8,1848.9,2696.0,9611.7,12307.7,6101.6,4119.5,10221.1,...,31228.7,-1683.9,314.4,-1369.5,1855.3,3440.8,5296.1,413.5,1494.9,1908.4
32,Papua,11472.4,8970.6,20443.1,34159.7,33698.2,67857.9,2117.2,4612.4,6729.6,...,17259.1,32846.1,45941.3,78787.4,6468.1,4744.1,11212.2,1731.4,4898.9,6630.3

In [15]:
# Take only total deforestasi data and add new sum column
outside_sumatera_data_deforestasi = outside_sumatera_data.filter(like='deforestasi')
outside_sumatera_data_deforestasi.insert(0, 'provinsi', data['provinsi'])
outside_sumatera_data_deforestasi['sum'] = outside_sumatera_data_deforestasi.iloc[:, 1:].sum(axis=1)

In [16]:
outside_sumatera_data_deforestasi

,provinsi,deforestasi_1314,deforestasi_1415,deforestasi_1516,deforestasi_1617,deforestasi_1718,deforestasi_1819,deforestasi_1920,sum
10,DKI Jakarta,0.0,0.0,0.0,-0.8,0.0,0.0,0.0,-0.8
11,Jawa Barat,-14880.5,6060.0,0.0,-188.0,6388.5,4977.4,0.0,2357.4
12,Jawa Tengah,-94.3,5231.4,0.0,0.0,3115.6,1904.0,0.0,10156.7
13,DI Yogyakarta,32.8,51.8,0.0,-270.2,589.8,326.4,0.0,730.6
14,Jawa Timur,7497.1,7749.2,0.0,0.0,8810.3,5804.7,0.0,29861.3
15,Banten,-266.1,1811.5,0.0,-5262.1,-283.1,83.4,34.3,-3882.1
16,Bali,130.2,77.5,7455.5,234.2,276.9,91.0,45.0,8310.3
17,Nusa Tenggara Barat,0.0,9083.2,22362.4,-14802.7,10236.4,15971.9,13007.9,55859.1
18,Nusa Tenggara Timur,108.8,13932.0,0.0,0.0,17689.9,3512.8,8289.5,43533.0
19,Kalimantan Barat,29919.6,40477.2,124956.0,19296.9,42291.4,24095.0,16334.5,297370.6
20,Kalimantan Tengah,58835.6,186642.0,98129.2,116782.8,27240.3,26240.2,6912.3,520782.4
21,Kalimantan Selatan,6938.5,46703.8,33125.1,-681.8,14368.6,8099.3,7547.2,116100.7
22,Kalimantan Timur dan Kalimantan Utara,38339.4,100930.8,108682.0,94981.8,65194.2,69584.6,10660.5,488373.3
23,Sulawesi Utara,3778.1,1307.5,2352.6,605.3,3902.6,260.8,399.4,12606.3
24,Sulawesi Tengah,4714.0,21376.3,26088.6,44523.9,21947.3,3791.8,9503.1,131945.0
25,Sulawesi Selatan,3354.0,10346.6,29937.2,9274.1,3598.2,2015.7,919.1,59444.9
26,Sulawesi Tenggara,2368.3,7116.7,15365.2,14956.3,30834.0,6557.2,3184.4,80382.1
27,Gorontalo,2586.1,14851.4,2242.5,-24.6,-339.6,378.1,1067.9,20761.8
28,Sulawesi Barat,929.0,2337.5,9524.7,1413.0,927.8,-228.8,215.7,15118.9
29,Maluku,912.2,4933.5,6900.5,1410.5,3716.9,1271.8,9267.4,28412.8
30,Maluku Utara,1569.1,11951.5,25792.2,22033.2,11820.2,2326.8,1609.8,77102.8
31,Papua Barat,1848.9,12307.7,10221.1,31228.7,-1369.5,5296.1,1908.4,61441.4
32,Papua,20443.1,67857.9,6729.6,17259.1,78787.4,11212.2,6630.3,208919.6

**Kesimpulan:**

* Data provinsi sumatera dan luar sumatera telah dibuat.
* Dibuat pula data Jumlah total deforestasi pertahun.

## 3. Analisis Data Statistik (Hypothesis Testing)

### 3.1. Menguji Hipotesis

**Hipotesis Pertama:**

**Jumlah deforestasi per tahun seluruh provinsi di sumatra > Jumlah deforestasi per tahun seluruh provinsi selain sumatra.**

Dalam uji variansi, jika rasio sampel dengan varians yang lebih besar dibandingkan dengan sample yang variansya lebih kecil <4, maka bisa kita assumsikan varians keduanya setara. Atau bisa menggunakan uji levene dimana H0 nya adalah kedua grup memiliki varians setara dan H1 nya adalah kedua grup memiliki varians yang berbeda. Jika di hasil levene test menunjukkan p-value < dari critical value (alpha) maka kita bisa menolak H0, dan sebaliknya.

In [18]:
# Create a sample for levene test
sample_1 = outside_sumatera_data_deforestasi['sum']
sample_2 = sumatera_data_deforestasi['sum']

In [19]:
# Levene test
levene_test = st.levene(sample_1, sample_2)

print(levene_test)
if levene_test.pvalue > 0.05:
    print("Tidak ada bukti untuk menolak hipotesis bahwa varians kedua kelompok sama.")
else:
    print("Hipotesis bahwa varians kedua kelompok berbeda signifikan.")

LeveneResult(statistic=0.12611726344437793, pvalue=0.7248971700965459)
Tidak ada bukti untuk menolak hipotesis bahwa varians kedua kelompok sama.

Dikarenakan p-value > dari critical value (alpha = 0.05) maka kita tidak bisa menolak H0 dan kedua sampel dianggap memiliki varians yang sama (equal_var = True)

* H0 (Null Hypothesis) : Jumlah deforestasi per tahun seluruh provinsi di sumatra > Jumlah deforestasi per tahun seluruh provinsi selain sumatra.
* H1 (Alternative Hypothesis) : Jumlah deforestasi per tahun seluruh provinsi di sumatra = Jumlah deforestasi per tahun seluruh provinsi selain sumatra

In [20]:
# ttest_ind for sample 1 and 2
alpha = 0.05

results = st.ttest_ind(sample_1, sample_2, equal_var=True)

print('p-value: ', results.pvalue)

if results.pvalue < alpha:
    print("Kita menolak hipotesis nol")
else:
    print("Kita tidak dapat menolak hipotesis nol")

p-value:  0.5485576567086605
Kita tidak dapat menolak hipotesis nol

**Kesimpulan:**

Jumlah deforestasi per tahun seluruh provinsi di sumatra > Jumlah deforestasi per tahun seluruh provinsi selain sumatra adalah **BENAR**

## Kesimpulan Umum

#### A. Pra-pemrosesan

Dari eksplorasi pra-pemrosesan data, dapat disimpulkan bahwa:
1. Dataframe menyangkut data deforestasi hutan di Indonesia berdasarkan provinsi pertahun 2013-2020.
2. Missing value berupa data (-) diubah menjadi 0 dan data duplikat tidak ditemukan.

#### B. Analisis Data Esksploratif (EDA)

Dari hasil analisis data esksploratif, dapat disimpulkan bahwa:
1. Data provinsi sumatera dilakukan slicing dan dibuat menjadi data baru. Data baru menyangkut total deforestasi pertahun.
2. Telah dibuat Jumlah total deforestasi pertrahun.
3. Data selain provinsi sumatera juga dibuat.

#### C. Analisis Data Statistik (Hypothesis Testing)

Dari hasil analisis pengujian hipotesis, dapat disimpulkan bahwa:
1. Hasil yang didapat dari uji hipotesis pertama yaitu Jumlah deforestasi per tahun seluruh provinsi di sumatra > Jumlah deforestasi per tahun seluruh provinsi selain sumatra adalah benar. Hipotesis tersebut tidak dapat ditolak.